### ISSUE TITLE
JSDoc: hide @param and @return tags in description

### ISSUE THREAD

**Issue by denis-sokolov** [marijnh/tern#563]
When showing a description for the function, Tern shows unexpectedly much.
I can see the `@param` and `@return` tags in the types of the appropriate arguments, and the resulting popup is quite messy due to their inclusion. Would it be possible to simplify it?

Observed behavior:
![1](https://cloud.githubusercontent.com/assets/113721/8146922/3bf3cf96-125d-11e5-8aa4-280a69904c57.png)

Expected behavior:
![2](https://cloud.githubusercontent.com/assets/113721/8146930/aae7d014-125d-11e5-8be9-f5b0f32b467a.png)

Thank you!

**Comment by marijnh** [comment]
My worry is that once we start seriously trying to massage comments into human-readable for we'll A) never be done, since it's a problem with a huge scope, and B) we'll have client modules complaining that we are stripping out or damaging information that they were interested in.

I am leaning towards letting clients take care of this. Alternatively, maybe add a query parameter that allows them to express a few simple transformations, such as the old behavior (strip everything after the first sentence).

There is someone [working](https://github.com/marijnh/tern/pull/555#issuecomment-111526034) on properly parsing the JSDocs and showing them as HTML, but I'm not entirely sure that is something everybody will like (the types are already shown anyway).

Comments welcome.

**Comment by denis-sokolov** [comment]
Alright that's reasonable enough, thank you.
